# Generated by Django 4.2 on 2026-01-15 11:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(default='Contact Us', max_length=100)),
                ('page_subtitle', models.CharField(blank=True, max_length=255)),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('office_address', wagtail.fields.RichTextField(blank=True)),
                ('phone_primary', models.CharField(blank=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('email_primary', models.EmailField(blank=True, max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254)),
                ('office_hours', wagtail.fields.RichTextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('map_embed_code', models.TextField(blank=True)),
                ('additional_content', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
