# Generated by Django 4.2 on 2026-01-16 09:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('press_date', models.DateField(help_text='Date of editorial')),
                ('author_names', models.CharField(blank=True, max_length=255)),
                ('short_title', models.CharField(max_length=255)),
                ('content', wagtail.fields.RichTextField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Editorial',
                'ordering': ['-press_date'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InterviewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('press_date', models.DateField(help_text='Date of interview')),
                ('author_names', models.CharField(blank=True, max_length=255)),
                ('short_title', models.CharField(max_length=255)),
                ('content', wagtail.fields.RichTextField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Interview',
                'ordering': ['-press_date'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('press_date', models.DateField(help_text='Date of news')),
                ('author_names', models.CharField(blank=True, max_length=255)),
                ('short_title', models.CharField(max_length=255)),
                ('content', wagtail.fields.RichTextField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-press_date'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PressIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(default='Press', help_text='Main page heading', max_length=100)),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text (optional)')),
            ],
            options={
                'verbose_name': 'Press Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PressReleasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('press_date', models.DateField(help_text='Date of press release')),
                ('author_names', models.CharField(blank=True, help_text='Author or speaker names (comma separated if multiple)', max_length=255)),
                ('short_title', models.CharField(help_text='Short title for card display', max_length=255)),
                ('content', wagtail.fields.RichTextField(help_text='Full press release content')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured (will be highlighted with green background)')),
            ],
            options={
                'verbose_name': 'Press Release',
                'verbose_name_plural': 'Press Releases',
                'ordering': ['-press_date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
