# Generated by Django 4.2 on 2026-01-16 11:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('pages', '0002_editorialpage_interviewpage_newspage_pressindexpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(default='Events', help_text='Main page heading', max_length=100)),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text about events')),
            ],
            options={
                'verbose_name': 'Event Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_type', models.CharField(choices=[('lecture', 'Lecture'), ('webinar', 'Webinar'), ('panel', 'Panel'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar')], default='lecture', help_text='Type of event', max_length=50)),
                ('event_format', models.CharField(choices=[('hybrid', 'Hybrid'), ('online', 'Online'), ('in-person', 'In-Person')], default='hybrid', help_text='Event format', max_length=50)),
                ('has_livestream', models.BooleanField(default=False, help_text='Does this event have livestream?')),
                ('event_start_date', models.DateField(help_text='Event start date')),
                ('event_start_time', models.TimeField(help_text='Event start time')),
                ('event_end_time', models.TimeField(help_text='Event end time')),
                ('event_title', models.CharField(help_text='Event title', max_length=255)),
                ('short_description', models.TextField(help_text='Short description for card display (max 300 characters)', max_length=300)),
                ('full_description', wagtail.fields.RichTextField(help_text='Full event description and details')),
                ('event_location', models.CharField(blank=True, help_text='Event location (if in-person or hybrid)', max_length=255)),
                ('registration_link', models.URLField(blank=True, help_text='External registration link (optional)')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['event_start_date', 'event_start_time'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
