# Generated by Django 4.2 on 2026-01-16 14:49

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('pages', '0003_eventindexpage_eventpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(default='About Us', help_text='Main page heading', max_length=100)),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text (optional)')),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HistoricalEventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_date', models.DateField(help_text='Date of the historical event')),
                ('event_title', models.CharField(help_text='Event title/heading', max_length=255)),
                ('event_description', wagtail.fields.RichTextField(help_text='Full event description')),
                ('event_image', models.ForeignKey(blank=True, help_text='Event image (recommended: 1200x800px)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Historical Event',
                'verbose_name_plural': 'Historical Events',
                'ordering': ['-event_date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
