# Generated by Django 4.2 on 2026-01-16 15:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('pages', '0005_galleryalbumpage_galleryindexpage_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(default='Articles', help_text='Main page heading', max_length=100)),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text (optional)')),
            ],
            options={
                'verbose_name': 'Article Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('article_type', models.CharField(choices=[('analysis', 'Analysis'), ('opinion', 'Opinion'), ('research', 'Research'), ('commentary', 'Commentary'), ('report', 'Report')], default='analysis', help_text='Type of article', max_length=50)),
                ('publish_date', models.DateField(help_text='Article publish date')),
                ('publish_time', models.TimeField(default='09:00', help_text='Article publish time')),
                ('author_name', models.CharField(blank=True, help_text='Article author name', max_length=255)),
                ('article_title', models.CharField(help_text='Article title', max_length=255)),
                ('short_description', models.TextField(help_text='Short description for card display', max_length=300)),
                ('full_content', wagtail.fields.RichTextField(help_text='Full article content')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured article')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Featured article image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-publish_date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
