# Generated by Django 4.2 on 2026-01-20 05:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('pages', '0006_articleindexpage_articlepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressAlbumPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('album_title', models.CharField(help_text='Album title', max_length=255)),
                ('album_date', models.DateField(help_text='Album date')),
                ('album_location', models.CharField(blank=True, help_text='Event location (e.g., Indira Bhawan | New Delhi)', max_length=255)),
                ('album_description', wagtail.fields.RichTextField(blank=True, help_text='Album description (optional)')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Album cover image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Press Album',
                'verbose_name_plural': 'Press Albums',
                'ordering': ['-album_date'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PressGalleryCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category_name', models.CharField(help_text='Category name (e.g., Editorials, Election Rally)', max_length=100)),
                ('category_description', wagtail.fields.RichTextField(blank=True, help_text='Category description (optional)')),
            ],
            options={
                'verbose_name': 'Press Gallery Category',
                'verbose_name_plural': 'Press Gallery Categories',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PressGalleryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(default='Press Gallery', help_text='Main page heading', max_length=100)),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text (optional)')),
            ],
            options={
                'verbose_name': 'Press Gallery Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='Photo caption (optional)', max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='press_images', to='pages.pressalbumpage')),
            ],
            options={
                'verbose_name': 'Press Image',
                'verbose_name_plural': 'Press Images',
            },
        ),
    ]
